### ISSUE TITLE
Crash without BOP on latest version

### ISSUE THREAD

**Issue by MerelSollie** [mrburger/Beta-Plus#6]
While the latest 1.14.4 version adden BOP-support, it stopped working without BOP.

```
java.lang.NoClassDefFoundError: biomesoplenty/api/biome/BOPBiomes
	at com.mrburgerus.betaplus.world.biome.support.BOPSupport.addBOP(BOPSupport.java:32) ~[?:0.5f] {}
	at com.mrburgerus.betaplus.world.biome.support.BOPSupport.init(BOPSupport.java:18) ~[?:0.5f] {}
	at com.mrburgerus.betaplus.world.biome.support.Support.<clinit>(Support.java:155) ~[?:0.5f] {}
	at com.mrburgerus.betaplus.world.biome.BiomeSelectorBetaPlus.<init>(BiomeSelectorBetaPlus.java:35) ~[?:0.5f] {}
	at com.mrburgerus.betaplus.world.beta_plus.BetaPlusGenSettings.createSettings(BetaPlusGenSettings.java:90) ~[?:0.5f] {}
	at com.mrburgerus.betaplus.world.beta_plus.WorldTypeBetaPlus.createChunkGenerator(WorldTypeBetaPlus.java:38) ~[?:0.5f] {}
	at net.minecraft.world.server.ServerWorld.lambda$new$3(ServerWorld.java:170) ~[?:?] {}
	at net.minecraft.world.server.ServerWorld$$Lambda$3376/190625379.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.<init>(World.java:99) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.<init>(ServerWorld.java:169) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:363) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:76) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
Caused by: java.lang.ClassNotFoundException: biomesoplenty.api.biome.BOPBiomes
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102) ~[modlauncher-3.2.0.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 15 more
```

**Comment by MerelSollie** [comment]
Closing this issue as it's stale for 5+ years and cluttering up my dashboard.
